import { AlertTriangle, ArrowLeft } from "lucide-react";
import { motion } from "motion/react";

interface DisclaimerPageProps {
  onBack: () => void;
}

export default function DisclaimerPage({ onBack }: DisclaimerPageProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="min-h-screen px-6 pt-28 pb-20"
    >
      <div className="max-w-3xl mx-auto">
        {/* Back button */}
        <button
          type="button"
          onClick={onBack}
          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-toss-orange transition-colors mb-10 group"
          data-ocid="disclaimer.back.button"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          Back to Home
        </button>

        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <div className="w-12 h-12 rounded-2xl bg-[oklch(0.73_0.15_55/0.12)] flex items-center justify-center">
            <AlertTriangle className="w-6 h-6 text-toss-orange" />
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-toss-orange/70 mb-1">
              Legal
            </p>
            <h1 className="text-4xl md:text-5xl font-black uppercase tracking-tight text-foreground">
              Disclaimer
            </h1>
          </div>
        </div>

        {/* Content */}
        <div className="glass-card rounded-3xl p-8 md:p-10 space-y-6">
          <div className="space-y-4">
            <h2 className="text-lg font-bold text-toss-orange uppercase tracking-wider">
              Entertainment Purpose Only
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              This tool is for entertainment and decision-making assistance
              only. Results are generated by a pseudo-random algorithm and
              should not be used for high-stakes decisions requiring certified
              randomness.
            </p>
          </div>

          <div className="w-full h-px bg-[oklch(0.26_0.013_240/0.4)]" />

          <div className="space-y-4">
            <h2 className="text-lg font-bold text-toss-orange uppercase tracking-wider">
              No Warranty
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The coin flip results are generated purely for convenience and
              fun. While we strive to provide a fair 50/50 experience, no
              warranty is made as to the suitability of this tool for any
              specific purpose, legal proceeding, or binding agreement.
            </p>
          </div>

          <div className="w-full h-px bg-[oklch(0.26_0.013_240/0.4)]" />

          <div className="space-y-4">
            <h2 className="text-lg font-bold text-toss-orange uppercase tracking-wider">
              No Data Storage
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The coin flip results are not stored or tracked on any server. All
              session data exists only within your browser tab and is cleared
              when you navigate away or close the page. Note: Third-party
              advertising services such as Google AdSense may store cookies or
              identifiers on your device for ad personalization purposes. Please
              see our Privacy Policy for details.
            </p>
          </div>

          <div className="w-full h-px bg-[oklch(0.26_0.013_240/0.4)]" />

          <div className="space-y-4">
            <h2 className="text-lg font-bold text-toss-orange uppercase tracking-wider">
              Responsible Use
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Use this tool responsibly. The developers of Toss are not liable
              for any decision, outcome, or consequence arising from use of this
              application. If you are making a high-stakes or legally
              significant decision, please consult appropriate professional
              advice.
            </p>
          </div>

          <div className="w-full h-px bg-[oklch(0.26_0.013_240/0.4)]" />

          <div className="space-y-4">
            <h2 className="text-lg font-bold text-toss-orange uppercase tracking-wider">
              Third-Party Advertising
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              This site may display advertisements served by Google AdSense and
              other third-party advertising networks. We are not responsible for
              the content of these advertisements. Third-party vendors,
              including Google, may use cookies to serve ads based on your prior
              visits to this website or other websites. These cookies do not
              contain personally identifiable information.
            </p>
          </div>

          <div className="w-full h-px bg-[oklch(0.26_0.013_240/0.4)]" />

          <div className="space-y-4">
            <h2 className="text-lg font-bold text-toss-orange uppercase tracking-wider">
              Advertising &amp; FTC Disclosure
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Toss is an ad-supported website. We may receive compensation from
              displaying advertisements through Google AdSense. This does not
              affect the editorial content or the fairness of the coin flip
              tool.
            </p>
          </div>
        </div>

        {/* CTA back */}
        <div className="mt-10 text-center">
          <button
            type="button"
            onClick={onBack}
            className="orange-gradient text-[oklch(0.12_0.006_240)] font-bold uppercase tracking-widest text-sm px-8 py-3.5 rounded-full hover:shadow-[0_0_30px_oklch(0.73_0.15_55/0.6)] hover:-translate-y-0.5 transition-all duration-200"
            data-ocid="disclaimer.home.button"
          >
            Back to Home
          </button>
        </div>
      </div>
    </motion.div>
  );
}
